data: rmnist
seed: 42
cuda: True
gpu_ids:
  - 7
  - 7
  - 7
num_workers: 12

test_epoch: 40

rmnist:
  rows: 28
  columns: 28
  channels: 1
  timesteps: 10
  tanh: True
  digits: 
    - 1
    - 3
    - 4
    - 5
    - 7
    - 8
    - 9
  actions:
    - rotation
  #path: /home/asif/workspace/TangentDS/Sprites/npy/
  #path: /disk/scratch/asif/workspace/TangentDS/Sprites/npy/
  path: /disk/scratch1/asif/workspace/VariationalLiePrior/data/MNIST

trainer:
 batch_size_train: 24
 batch_size_test: 16
 num_epochs: 500
 PretrainEpochs: 80
 test_every: 20
 save_every: 20
 recon_term: 10
 resume: False
 resume_epoch: 80
 BetaV: 1
 BetaV1: 1
 BetaZ: 1
 BetaT: 2
 BetaVrecon: 1
 annealkl: False
 anneal_every: 100
 reconloss: l2
 lossVrecon: False
 temporalLoss: False
 actions: ???
 nm_seq: ???

 model:
  condnSonU: False
  useZ: False
  uselstmZ: True
  projection: True
  pretrain: False
  sequential: ???
  qv_x: qv_f_x1toT
  v_dim: 64
  h_dim: 64
  z_dim: 32
  nm_operators: 1
  network: conv
  decoder: conv
  coords: none
  L: 8
  u_dim: ???
  channels: ???
  width: ???
  height: ???
  timesteps: ???
  dynamics: Hamiltonian

 optim:
   lamda_gp: 10
   lr: 0.0005
   lr_policy: step
   step_size: 200
   gamma: 0.1
   beta1: 0.5
   beta2: 0.999


output_model: /disk/scratch1/asif/workspace/HALO/model
output_results: /disk/scratch1/asif/workspace/HALO/results

