data: sprites
seed: 314159
cuda: True
gpu_ids:
  - 2
  - 3
  - 4
num_workers: 12

test_epoch: 800
mode: train

sprites:
  rows: 64
  columns: 64
  channels: 3
  timesteps: ???
  tanh: True
  directions: 
    - front
    - left
    - right
  actions:
    - walk
    - spellcard
    - slash
  #path: /home/asif/workspace/TangentDS/Sprites/npy/
  #path: /disk/scratch/asif/workspace/TangentDS/Sprites/npy/
  path: /disk/scratch1/asif/workspace/HALO/data/Sprites/npy/

trainer:
 batch_size_train: 24
 batch_size_test: 16
 num_epochs: 800
 PretrainEpochs: 80
 test_every: 20
 save_every: 20
 recon_term: 1
 resume: False
 resume_epoch: 400
 BetaV: 1
 BetaV1: 1
 BetaZ: 1
 BetaT: 2
 annealkl: False
 reconloss: l2
 lossVrecon: True
 temporalLoss: False
 actions: ???
 nm_seq: ???

 model:
  condnSonU: False
  useZ: True
  uselstmZ: True
  projection: True
  pretrain: False
  sequential: ???
  qv_x: qv_f_x1toT
  v_dim: 36
  h_dim: 2048
  z_dim: 256
  nm_operators: 3
  network: conv
  decoder: conv
  coords: none
  L: 8
  u_dim: ???
  channels: ???
  width: ???
  height: ???
  timesteps: ???
  dynamics: Hamiltonian

 optim:
   lamda_gp: 10
   lr: 0.0002
   lr_policy: step
   step_size: 200
   gamma: 0.1
   beta1: 0.5
   beta2: 0.999



output_model: /disk/scratch1/asif/workspace/VariationalLiePrior/noprojection/model
output_results: /disk/scratch1/asif/workspace/VariationalLiePrior/noprojection/results
classifierPath: /disk/scratch1/asif/workspace/VariationalLiePrior/classifier_sprites

